use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use serde::Deserialize;
use tauri::{AppHandle, Manager, State, WebviewUrl, WebviewWindow, WebviewWindowBuilder};

use crate::webview::ChildWebviewManager;

const QUICK_ASK_WINDOW_ID: &str = "quick_ask_window";

#[derive(Debug, Deserialize)]
pub struct InjectQuestionPayload {
    /// Platform ID (e.g., "chatgpt", "claude")
    pub platform_id: String,
    /// Question text to inject
    pub question: String,
    /// JS injection script generated by frontend
    pub script: String,
}

/// Tauri command: 向指定平台注入问题并自动发送
///
/// 接收前端生成的注入脚本（包含登录检测、输入框填充、发送按钮点击逻辑）
/// 并执行注入。返回成功或错误信息（含 NOT_LOGGED_IN 特殊错误码）
#[tauri::command]
pub async fn inject_question_to_platform(
    _app: AppHandle,
    state: State<'_, ChildWebviewManager>,
    payload: InjectQuestionPayload,
) -> Result<String, String> {
    log::info!(
        "Quick Ask: 向平台 {} 注入问题 (长度: {} 字符)",
        payload.platform_id,
        payload.question.len()
    );

    let webview_id = format!("ai-chat-{}", payload.platform_id);

    log::debug!(
        "Quick Ask: 脚本预览: {}...",
        &payload.script[..payload.script.len().min(200)]
    );

    // 使用 ChildWebviewManager 的公开方法执行注入
    match state.inject_script(&webview_id, &payload.script) {
        Ok(_) => {
            log::info!("Quick Ask: 注入请求已提交到平台 {}", payload.platform_id);
            // 由前端轮询 get_child_webview_fragment 获取状态
            Ok(String::from("{\"success\":true}"))
        }
        Err(err) => {
            log::error!("Quick Ask: 注入失败，平台 {}: {}", payload.platform_id, err);
            Err(err)
        }
    }
}

/// 注册快速问答全局快捷键
///
/// 说明：当前全局快捷键插件不支持“仅修饰键”（如仅 Shift）作为热键，
/// 因此这里采用跨平台可用的备用组合键并做轻量节流，避免重复触发。
/// 默认快捷键：Ctrl+Shift+Space（macOS 上等价为 ⌃⇧Space）。
pub fn register_double_shift_hotkey(app: &AppHandle) -> Result<(), String> {
    use tauri_plugin_global_shortcut::{GlobalShortcutExt, Shortcut};

    // 统一使用 Ctrl+Shift+Space 作为快速问答的默认全局快捷键
    // 备注：避免与应用内已注册的 Ctrl+Shift+A 冲突
    let fallback_shortcut = "Ctrl+Shift+Space";

    let parsed = fallback_shortcut
        .parse::<Shortcut>()
        .map_err(|err| format!("快捷键解析失败 ({fallback_shortcut}): {err}"))?;

    let last_ts = Arc::new(Mutex::new(None::<Instant>));
    let app_for_callback = app.clone();

    app.global_shortcut()
        .on_shortcut(parsed, move |_app, _event, _shortcut| {
            // 轻量节流：忽略 300ms 内的重复触发（部分系统会在按住时重复上报）
            let now = Instant::now();
            let mut last = last_ts.lock().expect("failed to lock shortcut ts");
            if let Some(prev) = *last {
                if now.duration_since(prev) < Duration::from_millis(300) {
                    return;
                }
            }
            *last = Some(now);

            let app_cloned = app_for_callback.clone();
            tauri::async_runtime::spawn(async move {
                if let Err(err) = open_quick_ask_window_internal(&app_cloned) {
                    log::error!("快速问答窗口打开失败: {err}");
                }
            });
        })
        .map_err(|err| format!(
            "注册快速问答全局快捷键失败 ({fallback_shortcut}): {err}\n提示：系统/插件暂不支持仅 Shift 作为热键，已使用备用组合键"
        ))?;

    log::info!(
        "快速问答全局快捷键已注册：{}（注意：仅 Shift 暂不受支持，已自动启用备用组合键）",
        fallback_shortcut
    );
    Ok(())
}

/// Tauri command: 打开快速问答窗口
#[tauri::command]
pub async fn open_quick_ask_window(app: AppHandle) -> Result<(), String> {
    open_quick_ask_window_internal(&app)
}

/// Tauri command: 关闭快速问答窗口
#[tauri::command]
pub async fn close_quick_ask_window(app: AppHandle) -> Result<(), String> {
    if let Some(window) = app.get_webview_window(QUICK_ASK_WINDOW_ID) {
        window
            .close()
            .map_err(|err| format!("关闭快速问答窗口失败: {err}"))?;
    }
    Ok(())
}

fn open_quick_ask_window_internal(app: &AppHandle) -> Result<(), String> {
    let window = ensure_quick_ask_window(app)?;
    window
        .show()
        .map_err(|err| format!("显示快速问答窗口失败: {err}"))?;
    window
        .set_focus()
        .map_err(|err| format!("聚焦快速问答窗口失败: {err}"))?;

    Ok(())
}

fn ensure_quick_ask_window(app: &AppHandle) -> Result<WebviewWindow, String> {
    if let Some(window) = app.get_webview_window(QUICK_ASK_WINDOW_ID) {
        return Ok(window);
    }

    let builder = WebviewWindowBuilder::new(
        app,
        QUICK_ASK_WINDOW_ID,
        WebviewUrl::App("/quick-ask".into()),
    )
    .title("Quick Ask")
    .decorations(false)
    .always_on_top(true)
    .resizable(false)
    .visible(false)
    .transparent(true)
    .skip_taskbar(true)
    .inner_size(720.0, 200.0)
    .shadow(false);

    let window = builder
        .build()
        .map_err(|err| format!("创建快速问答窗口失败: {err}"))?;

    window
        .center()
        .map_err(|err| format!("快速问答窗口居中失败: {err}"))?;

    Ok(window)
}
